name: Smoke Tests - PR

on:
  pull_request:
    branches: [ master ]

jobs:
  RunTest:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar o projeto
        uses: actions/checkout@v3

    # instalar o javafile report
      - name: Instalar Java 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: 'maven'

    # instalar o chrome
      - name: Instalar Chrome
        uses: browser-actions/setup-chrome@latest

    # instalar o chrome driver
      - name: Instalar o Chrome Driver
        uses: nanasess/setup-chromedriver@v1
      - run: |
          export DISPLAY=:99
          chromedriver --url-base=/wd/hub &
          sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 & # optional

    # executar os teste
      - name: Run Test
        run: mvn test -Dtest=RunCucumber -Dbrowser=chrome-ci -Dcucumber.options="--tags @login-sucesso"


      # gerar o relatorio
      - name: Gerar relatório
        if: always()
        run: mvn cluecumber-report:reporting


      - name: Arquivar relatório
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: report-tests
          path: '**/formated-report/'

      - name: Enviar notificação Discord - Sucesso
        if: ${{ success() }}
        uses: rjstone/discord-webhook-notify@v1
        with:
          severity: info
          details: Test Succeeded!
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}



      - name: Enviar notificação Discord - Falha
        if: ${{ failure() }}
        uses: rjstone/discord-webhook-notify@v1
        with:
          severity: error
          details: Test Failed!
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}





